repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args: [--maxkb=10000]
      - id: check-json
        exclude: .vscode
      - id: check-case-conflict
      - id: detect-private-key
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: fix-encoding-pragma
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.2.1
    hooks:
      - id: autoflake

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        exclude: ^migrations/|^uploads/|^scripts/|^logs/|^docs/|^dist/|^build/

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        language_version: python3
        exclude: ^migrations/|^uploads/|^scripts/|^logs/|^docs/|^dist/|^build/
