version: '3'
services:
  dailycheckin:
    image: sitoi/dailycheckin:latest
    container_name: dailycheckin
    restart: always
    tty: true
    volumes:
      - ./config.json:/dailycheckin/config.json
      - ./logs:/dailycheckin/logs