version: '3'
services:
  dailycheckin:
    build:
      context: .
    image: docker.pkg.github.com/sitoi/dailycheckin/dailycheckin:latest
    container_name: dailycheckin
    restart: always
    tty: true
    volumes:
      - ./config.json:/dailycheckin/config.json
      - ./logs:/dailycheckin/logs